INHERIT: mkdocs.yml
plugins:
  - awesome-pages
  - meta
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - print-site
  - include-markdown
