#!/bin/bash

################################################################################
# MicroShift Installation Script for macOS
################################################################################
# This script automates running MicroShift on macOS using Lima (Linux VM)
# with Fedora, providing a lightweight single-node OpenShift/Kubernetes
# environment for local development and testing.
#
# Prerequisites:
#   - macOS (Intel or Apple Silicon)
#   - Homebrew (https://brew.sh)
#   - At least 4 GB free RAM (8 GB+ recommended)
#   - At least 20 GB free disk space
#
# What it does:
#   1. Installs Lima (via Homebrew) if not present
#   2. Creates a Fedora VM with optimal resources for MicroShift
#   3. Installs MicroShift inside the VM
#   4. Installs oc/kubectl on your Mac and wires up kubeconfig
#   5. Waits for the cluster to be ready and prints access info
#
# Usage:
#   chmod +x install-microshift-mac.sh
#   ./install-microshift-mac.sh
#
# Author: OpenShift Lab Setup
# Date: July 2026
################################################################################

set -euo pipefail

################################################################################
# Configuration
################################################################################
VM_NAME="microshift"
VM_CPUS=4
VM_MEMORY_GB=4
VM_DISK_GB=20

FEDORA_VERSION="40"
MICROSHIFT_PORT=6443

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

################################################################################
# Colors & Helpers
################################################################################
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

print_header() {
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}$1${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
}

################################################################################
# Prerequisite Checks
################################################################################
check_prerequisites() {
    print_header "Checking Prerequisites"

    # Check macOS
    if [[ "$OSTYPE" != "darwin"* ]]; then
        print_error "This script is designed for macOS only."
        print_info "For Linux, use the existing install-openshift-local.sh instead."
        exit 1
    fi
    print_success "Running on macOS"

    # Check architecture
    ARCH=$(uname -m)
    print_info "Architecture: $ARCH"

    # Check if Rosetta 2 is needed (Apple Silicon but forcing x86_64)
    if [[ "$ARCH" == "arm64" ]]; then
        if ! /usr/bin/pgrep -q oahd 2>/dev/null; then
            print_warning "Rosetta 2 may be needed for some x86_64 containers."
            print_info "Install it with: softwareupdate --install-rosetta --agree-to-license"
        else
            print_success "Rosetta 2 is installed"
        fi
    fi

    # Check Homebrew
    if ! command -v brew &> /dev/null; then
        print_warning "Homebrew is required. Installing now..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    print_success "Homebrew is installed"

    # Check / install Lima
    if ! command -v limactl &> /dev/null; then
        print_info "Installing Lima via Homebrew..."
        brew install lima
    fi
    print_success "Lima is installed"
}

################################################################################
# Stop Existing VM (if any)
################################################################################
stop_existing_vm() {
    if limactl list 2>/dev/null | grep -q "$VM_NAME"; then
        local status
        status=$(limactl list --format '{{.Status}}' "$VM_NAME" 2>/dev/null || echo "")
        if [[ "$status" == "Running" ]]; then
            print_info "Stopping existing '$VM_NAME' VM..."
            limactl stop "$VM_NAME"
        fi
        print_info "Removing existing '$VM_NAME' VM..."
        limactl delete -f "$VM_NAME" 2>/dev/null || true
    fi
}

################################################################################
# Generate Lima Config
################################################################################
generate_lima_config() {
    local config_file="$1"

    print_info "Generating Lima config for Fedora ${FEDORA_VERSION}..."

    cat > "$config_file" <<EOF
# Lima configuration for MicroShift on Fedora ${FEDORA_VERSION}
# Generated by install-microshift-mac.sh
images:
  - location: "https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/${FEDORA_VERSION}/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-${FEDORA_VERSION}-1.14.qcow2"
    arch: "x86_64"
  - location: "https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/${FEDORA_VERSION}/Cloud/aarch64/images/Fedora-Cloud-Base-Generic.aarch64-${FEDORA_VERSION}-1.14.qcow2"
    arch: "aarch64"
cpus: ${VM_CPUS}
memory: "${VM_MEMORY_GB}GiB"
disk: "${VM_DISK_GB}GiB"
portForwards:
  - guestIP: "0.0.0.0"
    guestPort: ${MICROSHIFT_PORT}
    hostIP: "127.0.0.1"
    hostPort: ${MICROSHIFT_PORT}
EOF

    print_success "Lima config generated"
}

################################################################################
# Start VM
################################################################################
start_vm() {
    local config_file="$1"

    print_header "Starting Fedora VM via Lima"

    print_info "Launching Lima VM '$VM_NAME' (${VM_CPUS} CPUs, ${VM_MEMORY_GB} GB RAM, ${VM_DISK_GB} GB disk)..."
    print_info "This may take a few minutes for the first-time download and boot."

    limactl start --name "$VM_NAME" "$config_file"

    print_success "VM '$VM_NAME' is running"

    # Wait for VM to be fully ready
    print_info "Waiting for VM to be ready..."
    sleep 5

    # Test connectivity
    if limactl shell "$VM_NAME" -- uname -a > /dev/null 2>&1; then
        print_success "VM is accessible"
    else
        print_error "VM is not responding. Please check Lima status."
        exit 1
    fi
}

################################################################################
# Install MicroShift in VM
################################################################################
install_microshift() {
    print_header "Installing MicroShift in Fedora VM"

    print_info "Updating package repositories..."
    limactl shell "$VM_NAME" sudo dnf update -y --quiet

    print_info "Installing MicroShift..."
    limactl shell "$VM_NAME" sudo dnf install -y microshift

    print_success "MicroShift installed"

    print_info "Enabling and starting MicroShift..."
    limactl shell "$VM_NAME" sudo systemctl enable --now microshift

    print_info "Waiting for MicroShift to be ready (this may take 2-3 minutes)..."
    # MicroShift takes some time to fully initialize
    local retries=60
    local count=0
    while true; do
        if limactl shell "$VM_NAME" sudo test -f /var/lib/microshift/resources/kubeadmin/kubeconfig 2>/dev/null; then
            # Check if the API server is responding
            if limactl shell "$VM_NAME" -- sudo oc --kubeconfig /var/lib/microshift/resources/kubeadmin/kubeconfig get nodes 2>/dev/null | grep -q "Ready"; then
                print_success "MicroShift cluster is ready!"
                break
            fi
        fi
        count=$((count + 1))
        if [[ $count -ge $retries ]]; then
            print_warning "Timed out waiting for MicroShift to be ready."
            print_info "You can check status later with: limactl shell $VM_NAME -- sudo systemctl status microshift"
            break
        fi
        sleep 5
    done
}

################################################################################
# Install Host Tools (oc / kubectl)
################################################################################
install_host_tools() {
    print_header "Installing oc and kubectl on macOS"

    # Install openshift-cli (includes oc and kubectl)
    if ! command -v oc &> /dev/null; then
        print_info "Installing openshift-cli via Homebrew..."
        brew install openshift-cli
        print_success "openshift-cli installed"
    else
        print_info "oc is already installed: $(oc version --client 2>/dev/null || oc version 2>/dev/null | head -1)"
    fi

    # If kubectl is not included, install separately
    if ! command -v kubectl &> /dev/null; then
        print_info "Installing kubectl via Homebrew..."
        brew install kubectl
        print_success "kubectl installed"
    else
        print_info "kubectl is already installed: $(kubectl version --client 2>/dev/null | head -1)"
    fi
}

################################################################################
# Setup Kubeconfig on Host
################################################################################
setup_kubeconfig() {
    print_header "Setting Up Kubeconfig on macOS"

    local kube_dir="${HOME}/.kube"
    local kubeconfig_dest="${kube_dir}/microshift-kubeconfig"

    mkdir -p "$kube_dir"

    # Copy kubeconfig from VM to host
    print_info "Copying kubeconfig from VM..."
    limactl shell "$VM_NAME" -- sudo cat /var/lib/microshift/resources/kubeadmin/kubeconfig > "$kubeconfig_dest"

    # Replace the internal API server address with localhost
    sed -i '' "s|server: https://.*:6443|server: https://127.0.0.1:${MICROSHIFT_PORT}|g" "$kubeconfig_dest"

    chmod 600 "$kubeconfig_dest"
    print_success "Kubeconfig saved to: $kubeconfig_dest"

    # Warn if KUBECONFIG is not set
    if [[ -z "${KUBECONFIG:-}" ]]; then
        print_info "To use this cluster, set your kubeconfig:"
        echo "  export KUBECONFIG=${kubeconfig_dest}"
        print_info "Or merge it into your default kubeconfig:"
        echo "  export KUBECONFIG=${kubeconfig_dest}:${HOME}/.kube/config"
    fi
}

################################################################################
# Display Access Information
################################################################################
display_access_info() {
    print_header "MicroShift Cluster Access Information"

    echo ""
    echo -e "${GREEN}Cluster is ready!${NC}"
    echo ""
    echo "  Export KUBECONFIG:"
    echo "    export KUBECONFIG=${HOME}/.kube/microshift-kubeconfig"
    echo ""
    echo "  Verify the cluster:"
    echo "    oc get nodes"
    echo "    oc get pods -A"
    echo ""
    echo "  Useful commands:"
    echo "    limactl shell ${VM_NAME} -- sudo journalctl -u microshift -f    # Follow logs"
    echo "    limactl stop ${VM_NAME}                                          # Stop the VM"
    echo "    limactl start ${VM_NAME}                                         # Start the VM"
    echo "    limactl delete -f ${VM_NAME}                                     # Delete the VM"
    echo ""
    echo "  Default kubeconfig (read-only in VM):"
    echo "    /var/lib/microshift/resources/kubeadmin/kubeconfig"
    echo ""
    echo "  MicroShift is running on Fedora via Lima. The API server is"
    echo "  forwarded to localhost:${MICROSHIFT_PORT}."
    echo ""

    # Try to show cluster status
    if command -v oc &> /dev/null && [[ -f "${HOME}/.kube/microshift-kubeconfig" ]]; then
        print_info "Cluster nodes:"
        KUBECONFIG="${HOME}/.kube/microshift-kubeconfig" oc get nodes --insecure-skip-tls-verify 2>/dev/null || \
        KUBECONFIG="${HOME}/.kube/microshift-kubeconfig" kubectl get nodes --insecure-skip-tls-verify 2>/dev/null || \
        print_warning "Could not reach cluster API. The VM may still be starting up."

        print_info "Cluster pods:"
        KUBECONFIG="${HOME}/.kube/microshift-kubeconfig" oc get pods -A --insecure-skip-tls-verify 2>/dev/null || \
        KUBECONFIG="${HOME}/.kube/microshift-kubeconfig" kubectl get pods -A --insecure-skip-tls-verify 2>/dev/null || true
    fi
}

################################################################################
# Cleanup Temporary Files
################################################################################
cleanup() {
    rm -f /tmp/lima-microshift-config.yaml
}

################################################################################
# Main
################################################################################
main() {
    print_header "MicroShift Installation for macOS"

    print_info "This script will set up a Fedora VM via Lima and install MicroShift."
    echo ""

    local config_file="/tmp/lima-microshift-config.yaml"

    check_prerequisites
    stop_existing_vm
    generate_lima_config "$config_file"
    start_vm "$config_file"
    install_microshift
    install_host_tools
    setup_kubeconfig
    display_access_info

    cleanup

    echo ""
    print_success "MicroShift installation complete!"
    echo ""
    print_info "To start using your cluster, run:"
    echo "  export KUBECONFIG=${HOME}/.kube/microshift-kubeconfig"
    echo "  oc get nodes"
}

main "$@"
